### ISSUE TITLE
In stream load, the default value of strictMode is false.

### ISSUE THREAD

**Issue by ikaruga4600** [StarRocks/starrocks#1019]
After we updated starrocks from dorisdb@1.5 to starrocks@1.8,  we found that stream load a row contains long column (longger than schema limit) success, and the value changed to NULL.

In dorisdb@1.5, the load task would be failed.

Also in online document, default value of strictMode is true. (https://docs.starrocks.com/zh-cn/main/loading/StreamLoad)

I think this should be a bug.

**Comment by Dshadowzh** [comment]
I checked the code and this configuration is always False, this is a documentation error.

**Comment by ikaruga4600** [comment]
> I checked the code and this configuration is always False, this is a documentation error.

I just create a dorisdb cluster and perform a test.

```
sh show_fe_version.sh
Commit hash: 4bd9d39
Build type: RELEASE
Build time: 2021-05-11 14:18:30
Build user: jenkins@doris-sandbox07
Java compile version: java full version "1.8.0_202-b08"
```

```
MySQL [(none)]> select current_version();
+-------------------+
| current_version() |
+-------------------+
| 1.15.0 4bd9d39    |
+-------------------+
```

```
CREATE TABLE t (
  t varchar(1)
) ENGINE=OLAP
DUPLICATE KEY(t)
DISTRIBUTED BY HASH(t) BUCKETS 1
PROPERTIES (
"replication_num" = "1"
);
```

and get a failed result after stream load

```
Reason: the length of input is too long than schema. column_name: t; input_str: [1111111111] schema length: 1; actual length: 10; . src line: []; 
```

**Comment by imay** [comment]
@ikaruga4600 

Thank you very much to report it and give us a reproduce way.

In 1.15, non-vectorized load was used, however vectorized load was used in 1.18.
The key point is not the default strict value, but the default operation for the 'too long' string.

In my opinion, changing the default value is a big thing, because it will influence all users.
And treating 'too long' string as 'NULL' seems OK when strict_mode is false.

The original approach could be considered inappropriate and the current implementation corrects this approach.

**Comment by ikaruga4600** [comment]
@imay 
Thank you for your reply.
Strict mode have the same behavior as sql command line, and i think strict mode as default behavior may more fits user's anticipate.
I agree about changing the default value is a big thing, but in my position, i prefer default enable strict mode.

**Comment by imay** [comment]
@ikaruga4600 
Thanks for your advise. I think we should make it clear to users.
