### ISSUE TITLE
StarRocks update操作在哪个版本可以提供？

### ISSUE THREAD

**Issue by ulrican** [StarRocks/starrocks#10643]
## Feature request

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Johnsonginati** [comment]
StarRocks has started to support the Primary Key model since v1.19. The Primary Key model is suitable for the following scenarios in which data needs to be frequently updated in real-time.
You can see more detailed information in the documentation:https://docs.starrocks.com/en-us/latest/table_design/Data_model#primary-key-model

**Comment by ulrican** [comment]
主键模型进行合并的时候会覆盖所有字段，不支持按部分字段更新操作，需要update支持

**Comment by Dshadowzh** [comment]
In v2.2  SR support partial update using stream load/ broker load/ routine load as a preview feature. We suggest you use v2.3 to test this feature. You should use SSD as persistence storage.
