### ISSUE TITLE
[Enhancement] reduce pipeline engine driver poller thread cpu usage

### ISSUE THREAD

**Issue by liuyufei9527** [StarRocks/starrocks#12972]
## Enhancement

In my product cluster, When query hive external table, some split has slow io, but cpu is never lower than 100%. 
I use perf top and flame graph find out is the pipeline_driver_poller thread.

in pr [use _mm_pause and sched_yield instead of sleep](https://github.com/StarRocks/starrocks/pull/40)
_mm_pause usually use for busy wait spinning, but in this loop is check drivers status and can't save power.

I change back to use sleep get lower cpu usage, I think use sleep is better.

**Comment by mofeiatwork** [comment]
Thanks for feedback.

The busy polling mechanism is good at reduce latency, but with the cost of CPU cycles. Since there's only on thread working on the polling, in most cases it would not be the bottleneck.

But as you say, for some slow-io workloads, the cpu cost would be significant. 

We plan to optimize it into an event-driven style. Specifically, an IO-Scheduler is responsible for the io task, and the driver execution is driven by the IO event. In this pattern, there's no need for a poller, so we don't need to worry about the cpu cost any more.

**Comment by liuyufei9527** [comment]
@mofeiatwork Thanks for reply.

Look forward to the event-driven feature, may I ask whats the schedule of this. We plan use container cluster and current mechanism may have a major waste of cpu.
