### ISSUE TITLE
Table does not exist after recover database

### ISSUE THREAD

**Issue by colorfulu** [StarRocks/starrocks#13797]
### Steps to reproduce the behavior (Required)
```
create database db1;
use db1;
CREATE TABLE t1 (
    k1 INT,
    k2 INT,
    k3 INT SUM)
AGGREGATE KEY(k1,k2)
DISTRIBUTED BY HASH(k1);
show tables;
drop database db1;
recover database db1;
use db1;
show tables;

```

### Expected behavior (Required)
```
+---------------+
| Tables_in_db1 |
+---------------+
| t1            |
+---------------+
```
### Real behavior (Required)
`Empty set (0.00 sec)`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 0057ace |
+----------------------+
```

**Comment by srlch** [comment]
Problem:
This Problem was introduced by commit bdb4da184f0a7af1d0c1d262b1c7ac2f843f6716. This commit use Collections.unmodifiableSet instead of new HashSet to reduce the memory usage of fe. But the problem here is that Collections.unmodifiableSet is just return the view of nameToTable.keySet(). Before use the TableNames in recycleDatabase, nameToTable had been dropped and also the view of it would become empty, which cause this problem.

Solution:
We new the empty HashSet first in dropDb and add the table name one by one after remove the element in nameToTable.
