### ISSUE TITLE
Cannot create databases or users via UI in DBeaver

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#19398]
If you pick that starrocks is a mysql database, you can connect but can't "do" anything. 

<img width="903" alt="Screenshot 2023-03-11 at 8 43 15 PM" src="https://user-images.githubusercontent.com/749093/224524853-2bd03981-b2eb-4c40-a778-db21eb8ee1b6.png">

<img width="1150" alt="Screenshot 2023-03-11 at 8 45 05 PM" src="https://user-images.githubusercontent.com/749093/224524895-961842cf-7775-4c20-a98b-fc07ab197fa0.png">

**Comment by albertatcelerdata** [comment]
I tried the Driver for MySQL 8 and later and also Driver for MySQL 5.x+ and both do not work.

**Comment by Astralidea** [comment]
Hi, could you provide DBeaver version information and specific operation steps? This makes it easier for me to reproduce the problem.
From the error report, it seems that this problem is caused by the fact that although we pretend to be mysql, we have not actually implemented the system tables related to the mysql database. It may take some development to solve this problem.

**Comment by alberttwong** [comment]
DBeaver 23.0.0 which is the latest.  Just on "file" -> "new" and select one of the mysql entries. 

<img width="963" alt="Screenshot 2023-03-19 at 8 03 15 PM" src="https://user-images.githubusercontent.com/749093/226237020-94ac02f1-c926-4566-926f-db9211b0d5a8.png">
<img width="1022" alt="Screenshot 2023-03-19 at 8 03 43 PM" src="https://user-images.githubusercontent.com/749093/226237030-9503d651-dcb3-45ff-9422-12c86fde0a91.png">

**Comment by alberttwong** [comment]
Also tried on cloud.celerdata.com.   version UNKNOWN c2106cb0c.   same issue with db creation and user creation through UI.

**Comment by Astralidea** [comment]
We consider not supporting the creation of users on DBeaver. Because after discussion, we think that BI compatibility issues only need compatible queries. Concepts such as RBAC permissions will be introduced later. The need to create compatible users is relatively risky, so don’t do it for now. If you have strong needs and benefits, you can continue to give feedback.
