### ISSUE TITLE
1 FE and 1 BE Docker docker compose has StarRocks version UNKNOWN

### ISSUE THREAD

**Issue by ghost** [StarRocks/starrocks#19745]
Using `https://github.com/StarRocks/starrocks/blob/main/docker/docker-compose/docker-compose.yml`

When running `select current_version();`, I get `UNKNOWN c2106cb0c`.   There should be a version number shown.

**Comment by dirtysalt** [comment]
I guess the main reason is docker image of starrocks/fe-ubuntu(be-ubuntu):main has no released information there.

I've tried one like starrocks/fe-ubuntu:2.5.2, it shows
- https://hub.docker.com/r/starrocks/fe-ubuntu/tags
- https://hub.docker.com/r/starrocks/be-ubuntu/tags


<img width="922" alt="image" src="https://user-images.githubusercontent.com/1081215/226462556-458111b7-4c14-408f-bee3-9600c03a6cb8.png">

---

The main(or the latest) version usually does not come with specific readable version, so I guess it's sort of acceptable.

Or maybe we can fix https://github.com/StarRocks/starrocks/blob/main/docker/docker-compose/docker-compose.yml: don't use latest version, instead of released version like （2.5.2, 3.0.0).

**Comment by alberttwong** [comment]
Is there a way to enhance the build and release process to include that release information?
