### ISSUE TITLE
[Docs] Section should be renamed to "Stream Load HTTP interface"

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#21025]
File: [/docs/loading/Stream_Load_transaction_interface.md](https://docs.starrocks.io/en-us/latest/loading/Stream_Load_transaction_interface)

This is a weird description of the service.

**Comment by jaogoy** [comment]
Maybe you can give me more suggestion.

In my opinion, "Stream Load HTTP interface" is not so accurate. Because:
1. There is a HTTP interface for the original Stream Load, or we can call it Stream Load simple transaction HTTP interface.
2. Maybe it's more accurate to call the later interface "Stream Load 2PC transaction HTTP interface".

**Comment by alberttwong** [comment]
Other databases may call this a Data API that supports HTTP/HTTPS. https://www.mongodb.com/docs/atlas/api/data-api/

**Comment by amber-create** [comment]
@alberttwong Thank you for your feedback. And your info is really helpful for me to better understand this API. But based on discussions with PM, we will keep the name unchanged for now given other considerations.
