### ISSUE TITLE
create table fails when colocate group with the same name exists in other databases

### ISSUE THREAD

**Issue by haosu666** [StarRocks/starrocks#26692]
### Steps to reproduce the behavior (Required)
1. In version 2.5.7, create table with colocate group with the same name in db `test `and `development`

```
CREATE TABLE IF NOT EXISTS test.test_colocate(
    `id_listing` BIGINT NULL,
`m_pdp_views` BIGINT NULL,
`ds_night` DATE NULL,
`ds` DATE NULL
    ) ENGINE=olap
    DUPLICATE KEY (`id_listing`)
     PARTITION BY RANGE (ds_night) (START ('2021-07-11') END ('2023-07-12') EVERY (INTERVAL 1 MONTH) ) 
    DISTRIBUTED BY HASH (`id_listing`) BUCKETS 32
    PROPERTIES(
        "replication_num"="3",
"colocate_with" = "test_group_1"
    );
```

```
CREATE TABLE IF NOT EXISTS development.test_colocate(
    `id_listing` BIGINT NULL,
`m_pdp_views` BIGINT NULL,
`ds_night` DATE NULL,
`ds` DATE NULL
    ) ENGINE=olap
    DUPLICATE KEY (`id_listing`)
     PARTITION BY RANGE (ds_night) (START ('2021-07-11') END ('2023-07-12') EVERY (INTERVAL 1 MONTH) ) 
    DISTRIBUTED BY HASH (`id_listing`) BUCKETS 32
    PROPERTIES(
        "replication_num"="3",
"colocate_with" = "test_group_1"
    );

```

2. drop the above tables without force

```
mysql> drop table development.test_colocate;
Query OK, 0 rows affected (0.01 sec)


mysql> drop table test.test_colocate ;
Query OK, 0 rows affected (0.00 sec)
```

3. upgrade to 2.5.8, and create table in the 3rd db: test_c360, with the same colocate group name.

```
mysql> CREATE TABLE IF NOT EXISTS test_c360.test_colocate(
    ->     `id_listing` BIGINT NULL,
    -> `m_pdp_views` BIGINT NULL,
    -> `ds_night` DATE NULL,
    -> `ds` DATE NULL
    ->     ) ENGINE=olap
    ->     DUPLICATE KEY (`id_listing`)
    ->      PARTITION BY RANGE (ds_night) (START ('2020-07-11') END ('2022-07-12') EVERY (INTERVAL 1 MONTH) )
    ->     DISTRIBUTED BY HASH (`id_listing`) BUCKETS 32
    ->     PROPERTIES(
    ->         "replication_num"="3",
    -> "colocate_with" = "test_group_1"
    ->     );
ERROR 1064 (HY000): Unexpected exception: going to create a new group that has the same name 'test_group_1' with [2365495.26972029, 8158286.26975257], but these existed groups don't have the same `GroupId.grpId`

```

### Expected behavior (Required)
The table creation should not be blocked

### Real behavior (Required)
Failed to create table with colocate group.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.5.8

**Comment by nshangyiming** [comment]
Hi @haosu666, it's not a bug, let me explain, it's a little bit complicated.

Since we have supported colocate tables cross different databases in v2.5.8 by setting same `colocate_with` property when creating table, for compatibility reason, it will still show as different colocate groups in `show proc "/colocation_group"` result, but those groups has the same internally used `grpId` to indicate that the tables in each group should place in a colocated manner.

Here is an example, `13698` represents a table in database with id `13693` and `13456` represents a table in another database with id `13451`, to make them colocate in v2.5.8, we just need to specify the same property `"colocate_with"="db1cg1` when creating those two tables, and the same `grpId`, i.e. `13458` means that the two groups of different databases colocate with each other.
![image](https://github.com/StarRocks/starrocks/assets/107105845/1d244975-bfc3-4224-9e4d-4d09fbd94857)

But in v2.5.7 we didn't support this feature, so even two tables in different databases have the same `colocate_with` property, they didn't colocate and the corresponding colocate groups doesn't have the same `grpId`. So after upgading to v2.5.8, when creating a table in a third database with same `colocate_with` property, we cannot decide which group we should colocate with, i.e. to have the same `grpId` with, so an error like `...but these existed groups don't have the same GroupId.grpId` is raised.

To solve this problem, if you don't need to make the newly created table colocate with tables in other database, you can just use a different group name. If you do want to colocate with one of the existed colocate group, you should rename one of the existed group by executing `ALTER TABLE tbl SET ("colocate_with" = "new_group_name");` for all the tables in that group.

BTW, i see you actually drop the tables you created in the above example, but without `force` option, in this case, the colocate groups for those dropped tables still exists because the dropped tables are in the recycle bin in case that user dropped them unexpectly and may want to recover. So you can either drop them with `force` option or set `catalog_trash_expire_second` to a smaller value to clean the recycle bin in time, after that, the colocate groups will be dropped completely and the above error won't happen.
