### ISSUE TITLE
When doing "kubectl logs", it should show the FE or BE logs for that container

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#28619]
Right now the kubectl logs show very little data.   When a user executes kubectl logs for that container, it would default to show the FE or BE logs for that container.

**Comment by kevincai** [comment]
We have options to turn on the behavior that redirect FE/BE's application logs to pod console. It turns off by default, because we want to provide consistent experience as VM-based deployment, of which, the user get used to find the log from logdir.

Try add "LOG_CONSOLE = 1" environment variable in the CRD or chart values, all the logs will be redirected to console, can be viewed by `kubectl logs`

Related documents are still in catch-up.

**Comment by alberttwong** [comment]
I'd just say that when you're a k8s environment, you want to work the k8s way eg native way for that environment.  I don't think people will run half one way and half another.

**Comment by kevincai** [comment]
I agree. However, our log is chatty, and is important for trouble shoot, if user's infra doesn't have log collection service, it will be painful when log is lost.

It is a trade off.
