### ISSUE TITLE
异步物化视图数据更新范围问题

### ISSUE THREAD

**Issue by zyoo** [StarRocks/starrocks#30032]
新建物化视图：
create MATERIALIZED view test_mv distributed by hash(base_id) 
as select * from tb1 left join tb2 on tb1.id = tb2.outer_id

当tb1中有10条数据发生了变动，那相应的test_mv数据刷新时，是更新tb1中变化的10条数据和其相关数据？还是更新tb1变化的10条数据所在的分区的所有数据？还是更新tb1所有数据？

**Comment by LiShuMing** [comment]
> `当tb1中有10条数据发生了变动，那相应的test_mv数据刷新时，是更新tb1中变化的10条数据和其相关数据？还是更新tb1变化的10条数据所在的分区的所有数据？还是更新tb1所有数据？`

For this mv `test_mv `, if `tb1` has refreshed/changed,  all tbl1/tbl2's partitions' data will be refreshed into `test_mv` again, because you have not define a mv's partition with the base table.


if you create a mv `test_mv2` which is partitioned mv, then this mv is refreshed by increametal partitions of the bae table `tbl1`:
```
create MATERIALIZED view test_mv 
partitioned by tbl1.dt
distributed by hash(base_id)
as select * from tb1 left join tb2 on tb1.id = tb2.outer_id
```
