### ISSUE TITLE
Be hang when starting

### ISSUE THREAD

**Issue by SaintBacchus** [StarRocks/starrocks#3098]
### Steps to reproduce the behavior (Required)
In our scenoria, we create some big primary key table and use flink continuously write data into it. when I restarting the be process, it hanged.
It has about 950mb meta file on the disk
![image](https://user-images.githubusercontent.com/7404824/151100109-f06b8816-26d5-40ae-8d79-8ea84fdd8171.png)

### Expected behavior (Required)
Starting quickly

### Real behavior (Required)
![image](https://user-images.githubusercontent.com/7404824/151099777-e8ac3a3d-5581-4a59-8c9a-b7d867b82d4f.png)

the be process maybe hang in Rockdb::Seek the meta file and this function actually hang about 20min.

### StarRocks version (Required)
2.0.1

**Comment by decster** [comment]
Maybe you have too many tablets, please provide the result for this cmd
`
bin/meta_tool.sh --root-path=`pwd`/storage --operation=ls
`

**Comment by decster** [comment]
After some investigation, it seems the cause is rocksdb's DBIter::Seek(key) is very slow if the key does not exist and there are lots of deleted entries after `key`, so rocksdb will iterate those deleted keys until finding a valid next key. 
Unfortunately, if there are no pending rowsets, DBIter::seek('tprs_') will search next valid key in "trs_" range, if you have lots of deleted tablets (maybe caused by `drop table`), it will be *very* slow.
Will fix this in future PRs.

**Comment by decster** [comment]
Currently, you can use this cmd to compact meta data to remove deleted rows to prevent this issue.
```
bin/meta_tool.sh --root-path=`pwd`/storage --operation=compact_meta
```

**Comment by SaintBacchus** [comment]
OK, I will try it later with `compact_meta ` command
