### ISSUE TITLE
Should we persist profiles in some other storage

### ISSUE THREAD

**Issue by ikaruga4600** [StarRocks/starrocks#319]
## Enhancement
Currently query profiles stores in a in-memory queue, it's not enough for a long running server.
I cteate a PR to store profiles in somewhere like kafka.

**Comment by imay** [comment]
@ikaruga4600 

First of all, thank you very much for your contribution.

Could you describe more clearly the relevant background.

Because I see that the logic for writing to Kafka is introduced in the PR. There are a few points I think need to be discussed about this.

Is it necessary to introduce Kafka directly and are there other options? For example, we can pass the data out via webhook. This would ensure the flexibility of the whole solution. Either kafka or pulsa can be forwarded by an intermediate agent.

I see in the current PR that Kafka is introduced via a configuration file - is this a suitable solution? Is this a suitable solution? Because the configuration needs to be done by modifying the configuration file and also restarting the node. Also multiple FEs need to be configured manually, which may not be a particularly sensible approach.

3. kafka also has various authentication methods, how are these supported? How to handle when writing kafka fails.

Regarding these points above, I think we can discuss them in the follow up.

**Comment by ikaruga4600** [comment]
Thanks for you reply. @imay 

> Is it necessary to introduce Kafka directly and are there other options? For example, we can pass the data out via webhook. This would ensure the flexibility of the whole solution. Either kafka or pulsa can be forwarded by an intermediate agent.

Consider for other implements, i create a abstract method `void persist(List<Pair<String, String>> profiles)`. Is it flexable enough?

> I see in the current PR that Kafka is introduced via a configuration file - is this a suitable solution? Is this a suitable solution? Because the configuration needs to be done by modifying the configuration file and also restarting the node. Also multiple FEs need to be configured manually, which may not be a particularly sensible approach.

Yes, it's a problem. How about to extend the `alter` ddl, like 'alter system add/drop profile_storage' ? 

> kafka also has various authentication methods, how are these supported? 

Currently is it ok to just support simple SASL/PLAIN auth ? If yes, i will fix it in next commit.

> How to handle when writing kafka fails.
Currently i just print a warnning log because i thought the fails is not critical, is it sutiable?
