### ISSUE TITLE
set statement level variables through SET_VAR_STMT  hint

### ISSUE THREAD

**Issue by hagonzal** [StarRocks/starrocks#32024]
## Feature request

**Is your feature request related to a problem? Please describe.**
We use a query pool to handle connection to Starrocks.
When we execute queries (load, insert, update, select, etc) we use set variables:

set var1=val1;
set var2=val2;
select query...

This adds the set variables to the session established by the connection.
When we return the connection to the pool the set variables remain.

**Describe the solution you'd like**
Starrocks supports a hint to add set variables to SELECT statements:  /*+ set_var ( var1=a, var2=b, ...) */
This is very useful to only apply this set variables to the statement without actually modifying the session.

The request is to add another hint that applies to the entire query, not just select, that is placed at the start of the sql:
 /*+ set_var_stmt ( var1=a, var2=b, ...) */ query

This would work for all statements, including: select, update, insert, load

**Comment by packy92** [comment]
We currently do not support placing hints at the beginning of a sentence. This is because in some scenarios, the AST needs to be converted to SQL for persistence. Serializing the hint at the beginning of the sentence may result in issues where, if the version is downgraded, the hint cannot be parsed and may not take effect.
