### ISSUE TITLE
The query result is not as expected

### ISSUE THREAD

**Issue by hiliuxg** [StarRocks/starrocks#3347]
### Steps to reproduce the behavior (Required)
select a.dev_id
from
(
    select cid as dev_id
    from fx_ddl.aaaa
    where dt='2022-02-08'
    group by cid
)a
left join
(   
    select sid as dev_id
    from fx_ddl.bbbb
    where dt='2022-02-08'
    and sid is not null
    group by sid
)b on a.dev_id=b.dev_id
where b.dev_id is null
limit 5

### Expected behavior (Required)
![image](https://user-images.githubusercontent.com/39675622/153831925-1ab902ff-e4c2-49e0-a537-d81a53f0e1d0.png)

### Real behavior (Required)
![image](https://user-images.githubusercontent.com/39675622/153831969-a00751ec-a848-49ca-ab12-822335b0e77a.png)

### StarRocks version (Required)
 - 1.9.0

if the sql add the order by b.dev_id can fix the bug 
select a.dev_id
from
(
    select cid as dev_id
    from fx_ddl.aaaa
    where dt='2022-02-08'
    group by cid
)a
left join
(   
    select sid as dev_id
    from fx_ddl.bbbb
    where dt='2022-02-08'
    and sid is not null
    group by sid
)b on a.dev_id=b.dev_id
where b.dev_id is null
**order by b.dev_id**
limit 5

**Comment by HangyuanLiu** [comment]
Hello, there are currently two ways to verify the problem. 1. Upgrade to the latest version and verify whether the problem still exists (because it feels like this problem has occurred and has been fixed). 2. Provide a simple **insert data statement**, as well as a **table building statement** and a **query statement**. We will reply to you after internal verification.

**Comment by hiliuxg** [comment]
I upgrade the latest version first . thanks @HangyuanLiu
