### ISSUE TITLE
Understanding OlapScanConjunctsManager::build_scan_keys

### ISSUE THREAD

**Issue by zingdle** [StarRocks/starrocks#3761]
## General Question

In `OlapScanConjunctsManager::build_scan_keys`, `scan_keys` are built from `_column_value_ranges`. 

I'm curious about why it's checking `conditional_key_columns > 1` instead of `> 0` before extending the `scan_keys`:
https://github.com/StarRocks/starrocks/blob/6a4dda0fc52f8f8b750b07cc69c565c26f888826/be/src/exec/vectorized/olap_scan_prepare.cpp#L604-L611

So in the following example, selects from `one_column` will have a full scan then filter out by predicates because `conditional_key_columns == 1`, but selects from `two_column` with `conditional_key_columns == 2` will get narrower keys to scan from and introduces less IO.

I'm new to StarRocks and please correct me if I misunderstand something.

```sql
drop database if exists demo;
create database demo;
use demo;

CREATE TABLE one_column
(
	id1 INT NOT NULL
)
DUPLICATE KEY(id1)
DISTRIBUTED BY HASH(id1) BUCKETS 2
PROPERTIES("replication_num" = "1");

CREATE TABLE two_column
(
	id1 INT NOT NULL,
	id2 INT NOT NULL
)
DUPLICATE KEY(id1, id2)
DISTRIBUTED BY HASH(id1) BUCKETS 2
PROPERTIES("replication_num" = "1");

INSERT INTO one_column VALUES (0);
INSERT INTO one_column VALUES (1);
INSERT INTO one_column VALUES (2);
INSERT INTO one_column VALUES (3);
INSERT INTO one_column VALUES (4);

INSERT INTO two_column VALUES (0, 0);
INSERT INTO two_column VALUES (1, 1);
INSERT INTO two_column VALUES (2, 2);
INSERT INTO two_column VALUES (3, 3);
INSERT INTO two_column VALUES (4, 4);

SELECT * FROM two_column WHERE id1 = 2;
SELECT * FROM one_column WHERE id1 = 2;
```

**Comment by satanson** [comment]
@zingdle 
here ExtendScanKey is leveraged to convert range predicates of more than 1 columns into equal predicates.  the types of the columns must be enumerable, so the range per column are turned into a set of values, then the cartesian product are computed out from these sets,, we can build equal predicates on these elements of the cartesian product; for an example:
```
select * from t where a between  1 and 3 and b between 10 and 12;
```
- 1 to 3 range produces (1,2,3);
- 10 and 12 range produces(10,11,12);
- cartesian product are {(1,10),(2,10),(3,10),(1,11),(2,11),(3,11),(1,12),(2,12),(3,12)};
so the SQL above converted into 
```
select * from t where 
  (a=1 and b = 10) or
  (a=1 and b = 10) or
  (a=1 and b = 10) or
  (a=1 and b = 10) or
  (a=1 and b = 10) or
  (a=1 and b = 10) or
  (
```

**Comment by satanson** [comment]
@zingdle
here ExtendScanKey is leveraged to convert range predicates of more than 1 columns into equal predicates. the types of the columns must be enumerable, so the range per column are turned into a set of values, then the cartesian product are computed out from these sets,, we can build equal predicates on these elements of the cartesian product; for an example:
```
select * from t where a between  1 and 3 and b between 10 and 12;
```
- 1 to 3 range produces (1,2,3);
- 10 and 12 range produces(10,11,12);
- cartesian product are {(1,10),(2,10),(3,10),(1,11),(2,11),(3,11),(1,12),(2,12),(3,12)};
so the SQL above converted into
```
select * from t where 
  (a=1 and b = 10) or
  (a=1 and b = 11) or
  (a=1 and b = 12) or
  (a=2 and b = 10) or
  (a=2 and b = 11) or
  (a=2 and b = 12) or
  (a=3 and b = 10) or
  (a=3 and b = 11) or
  (a=3 and b = 12);
```
After equal predicates are built,we can create more TabletScanners to access storage engine, and each TabletScanner is assigned to an equal predicates.

when  conditional_key_columns is 1, it's no need to extend. In your example, the query on one_column do not perform full table scan, because short key index are employed to skip useless rows.
