### ISSUE TITLE
HTTP Stream Load breaks entirely if HTTP Keep Alive is enabled at the client side

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks#39918]
HTTP Stream Load breaks entirely if HTTP Keep Alive is enabled at the client side (this is default in Go).  There are some weird exceptions in the FEs, kinda like EOF.

@nferrario

**Comment by nferrario** [comment]
Update: this is trickier to replicate than I expected. The issue happens when I set `http.Transport.ExpectContinueTimeout` in Go, and it appears to only fail because there's a `307 Temporary Redirect` coming from the FE to tell us to use BE's API at port 8040 instead. However, after this redirection, the `100 Continue` response never comes, and that's why the error happens in the first place.

While this would seem like a bug in StarRocks, right now I'm looking at the network packets because I can't replicate this scenario in cURL. What's going into StarRocks appears to be correct, but Go's packet is clearly not exact to cURL's, so I need to find what's going on exactly.
