### ISSUE TITLE
Implement the aggregate function percentile_union_approx【Easy】

### ISSUE THREAD

**Issue by wuqiao** [StarRocks/starrocks#4023]
#  Requirement Description

Starrocks supports compute percentile by function `percentile_approx`, but the function only support number column.
If we do `percentile_approx` function on the percentile column, need:
1. do `percentile_union` on percentile column
2. do `percentile_approx_raw` on the result of step 1

so we want to support new aggregation function: `percentile_union_approx` 

The input: percentile column
The output: percentile_approx on percentile column which after aggregate
Function type: aggregate function

like on SQL:
```
select group_column, percentile_union_approx(percentile_column, 0.5) from test group by group_column;
```

the result equals:
```
select group_column, percentile_approx_raw(percentile_union(percentile_column), 0.5) from test group by group_column;
```

This function can refer to bitmap_union_count implementation

**Comment by zbtzbtzbt** [comment]
I pick! My name is zbt. I'm from china beijing. I am interested in OLAP, good at C++ programming and have not used StarRocks. I chose to solve this problem because I am familiar with function

**Comment by Im-Manshushu** [comment]
My name is WangMan. I'd like to pick this issue. I started using it very early StarRocks. From version 1.14 to 2.1.  I chose to solve this problem because I am familiar with using starrocks and  I am big data development engineer from beijing  and good at Java programming and and a little knowledge of C + + programming.I hope I can contribute a little to the community. Complete the task

**Comment by ylcq** [comment]
My name is YangLian, I have been working on machine learning algorithms development for 3 years using C++ programming; working on data development for 2.5 years using Java programming. I have been using StarRocks for 4 months. I am interested in OLAP and StarRocks and our company has been introduced StarRocks, so I chose to solve this issue to contribute to the community.

**Comment by chaixuqing** [comment]
I pick! My name is Xuqing Chai. I am a postgraduate student from BUPT. I have been learning on database kernel development for 1 year.  I have studied CMU 15-445 and MIT6.824, and I have read most of the source code of LevelDB. I'm currently studying CMU15-712, the main content of this course is reading VLDB papers. I am interested in OLAP, good at C++ programming, but have been using StarRocks. I chose to solve this issue because I want to contribute for StarRocks.

**Comment by Seaven** [comment]
Prepare
1. Learn the code about `bitmap_union_count` function in BE
2. Learn FE function analyze process to get how to call function

Develop:
1. Implement `percentile_approx_count` function
2. Implement `percentile_approx_count` call process in FE

Challenge(optional):
1. Replace `count(`percentile`)` function on materialized view.

**Comment by zbtzbtzbt** [comment]
> Prepare
> 
> 1. Learn the code about `bitmap_union_count` function in BE
> 2. Learn FE function analyze process to get how to call function
> 
> Develop:
> 
> 1. Implement `percentile_approx_count` function
> 2. Implement `percentile_approx_count` call process in FE
> 
> Challenge(optional, not required):
> 
> 1. Replace `count(percentile_column)` function in materialized view.

thanks, I plan to start do it in two days.

**Comment by Seaven** [comment]
> > Prepare
> > 
> > 1. Learn the code about `bitmap_union_count` function in BE
> > 2. Learn FE function analyze process to get how to call function
> > 
> > Develop:
> > 
> > 1. Implement `percentile_approx_count` function
> > 2. Implement `percentile_approx_count` call process in FE
> > 
> > Challenge(optional, not required):
> > 
> > 1. Replace `count(percentile_column)` function in materialized view.
> 
> thanks, I plan to start do it in two days.

I updated the title and contents
