### ISSUE TITLE
New Parser and Analyzer support cluster management statements【Easy】

### ISSUE THREAD

**Issue by wuqiao** [StarRocks/starrocks#4044]
# Requirement Description
The new Parser and the new Analyzer support cluster management statements

# Mentor
@HangyuanLiu 

# Registration procedure

**Step 1.** Add a comment when you sign up. The comment can be a brief self-introduction and reason for signing up, including what you do, what you're good at, what you're interested in and your technology stack, and how familiar you are with StarRocks. Example:

> I pick! My name is Johnny. I am from StarRocks and I have been working on database kernel development for 1 year. I am interested in OLAP, good at C++ programming, and have been using StarRocks for 6 months. I chose to solve this issue because I am familiar with execution engine.

**Step 2.** On your WeChat, add the StarRocks community assistant "**_StarRocks-1_**" as a WeChat friend and leave your GitHub ID. The assistant will invite you to a WeChat group based on the issue you picked.

**Step 3.** The mentor will communicate with all the participants who picked this issue and assign the task to the best match. 

# Before you start
1. Read the StarRocks [GitHub workflow](https://github.com/StarRocks/community/blob/main/Contributors/guide/workflow.md) carefully, which provides the configurations of BE and FE and describes how to submit a pull request.
2. To learn more about StarRocks, read [StarRocks documentation](https://github.com/StarRocks/docs/blob/main/TOC.md).

# Pull request requirements

1. After you complete code development, upload the code to the StarRocks code repo as a pull request (PR).

  - PR title format: **[SR GeekCamp] + PR title**
  - Labels ：[Geek Camp 2022/feature]
2. After you submit your PR, comment on the status of your PR submission as requested under the Pinned Issue [[StarRocks geek Camp 2022] ](https://github.com/StarRocks/starrocks/issues/4008)page.

  - Comment format: **"I have finished Issue #" + PR link id**

**Comment by blackstar-baba** [comment]
LGTM ! My name is `blackstar-baba`. I am from `Peixi-IOT` and I have been working on database kernel development for 1 year. I am interested in OLAP, good at Java programming, and have some experience in simple C++ programming, and have been using StarRocks for 4 months. I also solved #3180 & #3181 issues.  I chose to solve this issue because I am familiar with Planner.

**Comment by happut** [comment]
I pick! My name is Wang Fei. I am developer of BEIKE. I'm interested the all kinds of advanced technology of OLAP,good at Java programming. I've bean using StarRocks for 6 months. I chose to solve this issue because the team which I'm working at is using StarRocks deeply. With solving this issue I can improve my ability of StarRocks and improve StarRocks together.
