### ISSUE TITLE
select not empty [] result error

### ISSUE THREAD

**Issue by lvchenyang-maker** [StarRocks/starrocks#4440]
### Steps to reproduce the behavior (Required)
  1. 
```
select [1, 2.0, '3', null]
```

### Expected behavior (Required)
["1","2.0","3",null]
### Real behavior (Required)
```
+--------------------+
| [1, 2, '3', NULL]  |
+--------------------+
| ["1","2","3",null] |
+--------------------+
```
### StarRocks version (Required)
```
+------------------------+
| current_version()      |
+------------------------+
| BRANCH_RELEASE a1ae0dc |
+------------------------+
```

**Comment by kangkaisen** [comment]
<img width="808" alt="Screen Shot 2022-03-25 at 3 43 57 PM" src="https://user-images.githubusercontent.com/9894906/160076547-d9878194-3b3c-4605-a0c0-af96af356131.png">

**Comment by kangkaisen** [comment]
The decimal scale is wrong.

**Comment by satanson** [comment]
@kangkaisen @lvchenyang-maker  

Because multi-width decimal types co-exist internally, in order to avoid to use exaggerated common types to process binary predicates and arithmetic operations,  untyped decimal literals adopt the narrowest decimal types to process.

for examples:
select * from t where c=3.000;
if c is decimal64(18, 2), if we use decimal32(4,3) as the type of 3.000, then the common type is decimal128(19, 3); if we use decimal32(1,0) instead, then the common type is decimal64(18,2). using the narrowest decmial type for untyped decimal literal is efficient and the predicates can push down to storage-engine.

**Comment by satanson** [comment]
@kangkaisen @lvchenyang-maker  

Because multi-width decimal types co-exist internally, in order to avoid to use exaggerated common types to process binary predicates and arithmetic operations,  untyped decimal literals adopt the narrowest decimal types to process.

for examples:
select * from t where c=3.000;
if c is decimal64(18, 2), if we use decimal32(4,3) as the type of 3.000, then the common type is decimal128(19, 3); if we use decimal32(1,0) instead, then the common type is decimal64(18,2). using the narrowest decmial type for untyped decimal literal is efficient and the predicates can push down to storage-engine.
