### ISSUE TITLE
Support query from databricks unity catalog

### ISSUE THREAD

**Issue by Youngwb** [StarRocks/starrocks#45054]
## Feature request

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by epa095** [comment]
This was closed as completed, but the PR don't seem like it got merged. Does it make sense to reopen this? It certainly seems useful to be able to interact with unity catalog as an external catalog, since databricks has now open sourced it, it they do not provide any hive metastore compatible endpoint for their unity catalog managed data.
