### ISSUE TITLE
FE start failed with replay routine load job failed

### ISSUE THREAD

**Issue by gengjun-git** [StarRocks/starrocks#5620]
### Steps to reproduce the behavior (Required)
create lots of routine load job on broken kafka env.

### Expected behavior (Required)
FE restart successfully.

### Real behavior (Required)
FE restart failed.

### StarRocks version (Required)
 - all

**Comment by gengjun-git** [comment]
The reason is that update log is written ahead of create log
```shell
log/fe.log:2022-04-28 14:23:22,915 INFO (stateListener|80) [RoutineLoadManager.replayChangeRoutineLoadJob():539] start to replay routine load, id : 1702123, state: PAUSED
log/fe.log.20220426-1:2022-04-26 16:34:26,933 INFO (starrocks-mysql-nio-pool-4|189) [TxnStateCallbackFactory.addCallback():41] add callback of txn state : 1702123. current callback size: 3
log/fe.log.20220426-1:2022-04-26 16:34:29,912 WARN (Routine load scheduler|55) [KafkaRoutineLoadJob.unprotectNeedReschedule():292] ROUTINE_LOAD_JOB=1702123, error_msg={Job failed to fetch all current partition with error [Failed to send proxy request: failed to send proxy request: [no partition in this topic]]}
log/fe.log.20220426-1:2022-04-26 16:34:29,913 INFO (Routine load scheduler|55) [RoutineLoadJob.unprotectUpdateState():1068] ROUTINE_LOAD_JOB=1702123, current_job_state={NEED_SCHEDULE}, desire_job_state={PAUSED}, msg={ErrorReason{errCode = 4, msg='Job failed to fetch all current partition with error [Failed to send proxy request: failed to send proxy request: [no partition in this topic]]'}}
log/fe.log.20220426-1:2022-04-26 16:34:29,913 WARN (Routine load scheduler|55) [RoutineLoadJob.unprotectUpdateState():1081] routine load job 1702123-lowcard_testz changed to PAUSED with reason: ErrorReason{errCode = 4, msg='Job failed to fetch all current partition with error [Failed to send proxy request: failed to send proxy request: [no partition in this topic]]'}
log/fe.log.20220426-1:2022-04-26 16:34:48,249 INFO (Routine load scheduler|55) [RoutineLoadJob.unprotectUpdateState():1109] ROUTINE_LOAD_JOB=1702123, current_job_state={PAUSED}, msg={job state has been changed}, is replay={false}
log/fe.log.20220426-1:2022-04-26 16:34:48,641 INFO (starrocks-mysql-nio-pool-4|189) [RoutineLoadManager.addRoutineLoadJob():217] create routine load job: id: 1702123, name: lowcard_testz
```

**Comment by padmejin** [comment]
1. A user creates a new routine job from a client.
2. The request is handled by a thread, transforming the SQL to a RoutineLoadJob and then put it into a map of the `RoutineLoadManager` class in a function guarded by a write lock.
3. The `RoutineLoadTaskScheduler` thread happens to start a new loop just then by getting all the routine load jobs from the map in the `RoutineLoadManager` class. Since there's no read lock, it finds the newly added job and schedulers it. Then it writes a journal on a state change of this new job.
4. The SQL executor thread is a bit slower in handling the new job. In the end, it writes a journal on creating a new job.

From the follower's view, the journal of creating a job is behind the journal of changing its state. As a result, it failed to replay the former journal because of failure to change the state of a non-existence job.

The solution is simple, just add a read lock would be enough. Since creating a routine job is not a frequently operation, it won't be too much cost for the scheduler thread.
