### ISSUE TITLE
Remove AlterJob and related code

### ISSUE THREAD

**Issue by decster** [StarRocks/starrocks#8272]

**Comment by Astralidea** [comment]
This work has already started in version 2.4, the relevant PR #6947.
In order to maintain version compatibility, some preparatory work has been done, and it is best to do another part of the code deletion work in version 2.5. Because the old one did not have a cleanup mechanism before, the image part should be cleared first in the preparation work, so that users can get compatibility as long as they do not upgrade across versions.
