### ISSUE TITLE
Routine load be crashed with rd_kafka_broker_destroy_final

### ISSUE THREAD

**Issue by gengjun-git** [StarRocks/starrocks#871]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Expected behavior (Required)
Haven't found a stable way to reproduce

### Real behavior (Required)
![image](https://user-images.githubusercontent.com/54172532/138709341-fa4070b4-0476-4b93-87d2-140bf906c5b9.png)

### StarRocks version (Required)
 - 1.18.4

**Comment by trueeyu** [comment]
In order to solve the problem of memory leakage under lz4, upgrade the librdkafka library from version (librdkafka-0.11.6-RC5.tar.gz ) to version (librdkafka-1.7.0.tar.gz ). But it will crash under version 1.5.0/1.7.0/1.8.0/

**Comment by trueeyu** [comment]
It whill not crash in version(librdkafka-0.11.6-RC5.tar.gz)

**Comment by trueeyu** [comment]
```
I1121 10:43:32.134096  5349 load_channel_mgr.cpp:328] Cleaning timed out load channels
I1121 10:43:32.134112  5349 load_channel_mgr.cpp:361] Memory consumption(bytes) limit=15914917232 current=0 peak=556
I1121 10:43:32.434504  1639 heartbeat_server.cpp:57] get heartbeat from FE.host:172.26.92.155, port:29927, cluster id:1926549673, counter:180061
I1121 10:43:36.451244  5343 data_consumer_pool.cpp:144] remove data consumer ea4eb60e45e2e672-e4e117d852c23ea5, since it last visit: 0, now: 1637462616
I1121 10:43:36.451512  5343 data_consumer_pool.cpp:144] remove data consumer db4d1982315aa112-c6373b425aaff0b6, since it last visit: 0, now: 1637462616
```

**Comment by trueeyu** [comment]
If thread_1 (rdkafka_broker_thread_main) is executing rd_kafka_metadata_refresh_known_topics (which will select one rbk to fetch topics), and then thread_2 (rdkafka_broker_thread_main which create the rbk ) exit, finally the thread_1 will destroy the rbk, so the check is problematic

starrocks_be: rdkafka_broker.c:5412: rd_kafka_broker_destroy_final: Assertion `thrd_is_current(rkb->rkb_thread)' failed

https://github.com/edenhill/librdkafka/blob/c0cfc24cce8b77a1e42d9668dd1cfd015bbf0d6b/src/rdkafka_broker.c#L5391

There is no problem with the very old version, because the old version is preferentially select it's own rb , but the new version  select according to the weight.
